server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html index.htm;

    # Frontend Routes (React Router ke liye)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # API Requests Proxy (Jo /api se start hongi, unhe backend-gateway par bhej dega)
    location /api/ {
        proxy_pass http://collabsphere_api_gateway:5000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}